% auto generated by Experiment.py

stem1107 = '../../../2012-11-07-Time_series_x2/Time_data/';

experimentName = 'rtTA Series';
device_name = 'rtTA';
inducer_name = 'Hours';
load('../../controls/CMtriplicate.mat');
input = channel_named(CM, 'Yellow');
output = channel_named(CM, 'Blue'); % Treating Dox induction as output
constitutive = channel_named(CM, 'Red');
level_file_pairs = ...
 {12,  {[stem1107 'T12-1_H10_H10_P3.fcs'], [stem1107 'T12-2_H12_H12_P3.fcs']};
  16,  {[stem1107 'T16-1_A2_A02_P3.fcs'],  [stem1107 'T16-2_D2_D02_P3.fcs']};
  18,  {[stem1107 'T18-1_A9_A09_P3.fcs'],  [stem1107 'T18-2_D9_D09_P3.fcs']};
  20,  {[stem1107 'T20-1_B4_B04_P3.fcs'],  [stem1107 'T20-2_E4_E04_P3.fcs']};
  22,  {[stem1107 'T22-1_B11_B11_P3.fcs'], [stem1107 'T22-2_E11_E11_P3.fcs']};
  24,  {[stem1107 'T24-1_A2_A02_P3.fcs'],  [stem1107 'T24-2_C2_C02_P3.fcs']};
  26,  {[stem1107 'T26-1_A2_A02_P3.fcs'],  [stem1107 'T26-2_D8_D08_P3.fcs']};
  28,  {[stem1107 'T28-1_A9_A09_P3.fcs'],  [stem1107 'T28-2_E3_E03_P3.fcs']};
  30,  {[stem1107 'T30-1_B4_B04_P3.fcs'],  [stem1107 'T30-2_E10_E10_P3.fcs']};
  42,  {[stem1107 'T42-1_A9_A09_P3.fcs'],  [stem1107 'T42-2_C9_C09_P3.fcs']};
  48,  {[stem1107 'T48-1_B11_B11_P3.fcs'], [stem1107 'T48-2_F5_F05_P3.fcs']};
  58,  {[stem1107 '../T58/T58-1_Dox_P3.fcs'] [stem1107 '../T58/T58-2_Dox_P3.fcs']};
  60,  {[stem1107 'T60-1_C6_C06_P3.fcs'],  [stem1107 'T60-2_F6_F06_P3.fcs']};
  63,  {[stem1107 'T63-1_B4_B04_P3.fcs'],  [stem1107 'T63-2_D4_D04_P3.fcs']};
  69,  {[stem1107 'T69-1_C6_C06_P3.fcs'],  [stem1107 'T69-2_F12_F12_P3.fcs']};
  72,  {[stem1107 'T72-1_D1_D01_P3.fcs'],  [stem1107 'T72-2_G7_G07_P3.fcs']}};
experiment = Experiment(experimentName,{inducer_name}, level_file_pairs);
fprintf('Starting analysis...\n');
bins = BinSequence(4,0.1,10,'log_bins');
AP = AnalysisParameters(bins,{'input',input; 'output',output; 'constitutive' constitutive});
AP=setMEFLPerPlasmid(AP,1000');
AP=setMinValidCount(AP,10');
AP=setPemDropThreshold(AP,5');
AP=setUseAutoFluorescence(AP,false');
sampleresults = process_data(CM,experiment,AP);
results = summarize_data(CM,experiment,AP,sampleresults);

OS = OutputSettings('Fine',device_name,'');
plot_bin_statistics(sampleresults,OS);

expression = get_channel_results(results,'output');
counts = getBinCounts(results);
active = getFractionActive(results);
n_levels = size(expression,2);

o_index = find(CM,output); % Determine data column from ColorModel

fraction_active = zeros(n_levels,1);
mean_active_expression = zeros(n_levels,1);
n_samples = 0;
sample_inductions = []; sample_activity = []; sample_expression = [];
for i=1:n_levels,
    which = counts(:,i)>0;
    fraction_active(i) = sum(counts(which,i) .* active(which,i)) / sum(counts(which,i));
    which = active(:,i) > 0.9;
    mean_active_expression(i) = 10.^wmean(log10(expression(which,i)),counts(which,i));
    block_start = n_samples+1;
    for j=1:numel(sampleresults{i}),
        n_samples = n_samples+1;
        sample_inductions(n_samples) = level_file_pairs{i,1};
        sample = sampleresults{i}{j};

        which = sample.BinCounts>getMinValidCount(AP);
        sample_activity(n_samples) = sum(sample.BinCounts(which) .* sample.FractionActive(which)) / sum(sample.BinCounts(which));
        which = sample.FractionActive>0.9;
        sample_expression(n_samples) = 10.^wmean(log10(sample.Means(which,o_index)),sample.BinCounts(which));
    end
    std_fraction_active(i) = std(sample_activity(block_start:n_samples));
    std_active_expression(i) = geostd(sample_expression(block_start:n_samples));
end

induction_levels = [level_file_pairs{:,1}];

h = figure('PaperPosition',[1 1 5 3.66]);
plot(sample_inductions,sample_activity,'*'); hold on;
plot(induction_levels,fraction_active,'r-');
plot(induction_levels,fraction_active+2*std_fraction_active','r--');
plot(induction_levels,fraction_active-2*std_fraction_active','r--');
xlabel('Time (hours)');  ylabel('Fraction Active');
xlim([0 75]); ylim([0 1]);
title('rtTA fraction active vs time');
outputfig(h,'rtTA-fraction-active');

h = figure('PaperPosition',[1 1 5 3.66]);
plot(sample_inductions,sample_expression,'*'); hold on;
plot([level_file_pairs{:,1}],mean_active_expression,'r-');
plot([level_file_pairs{:,1}],mean_active_expression.*(10.^(2*log10(std_active_expression'))),'r--');
plot([level_file_pairs{:,1}],mean_active_expression./(10.^(2*log10(std_active_expression'))),'r--');
xlabel('Time (hours)');  ylabel('OFP MEFL');
xlim([0 75]);
title('rtTA active population mean MEFL vs time');
outputfig(h,'rtTA-population-mean');
set(gca,'YScale','log');
outputfig(h,'rtTA-population-mean-log');
 

save('-V7','rtTA-series-Fine.mat','CM','experiment','AP','sampleresults','results','fraction_active','mean_active_expression','std_active_expression','sample_expression');

%%% Find the expression model:
addpath('..');
samples = [sample_inductions' sample_expression' sample_activity'];

fn = @(params)(expression_error(params(1),params(2),params(3),params(4),samples));
expression_fit = fminsearch(fn,[18 12 1e5 0.7]);
% ans = [36.5 9 6.9e5 0.65]
div_time = expression_fit(1);
shock_time = expression_fit(2);
mean_divisions = (72-shock_time-(div_time/2))/div_time
% ans = 1.26

[model_levels model_acts] = expression_model(expression_fit(1), expression_fit(2), expression_fit(3), expression_fit(4), 72, 0.1);

h = figure('PaperPosition',[1 1 5 3.66]);
plot(sample_inductions,sample_expression,'*'); hold on;
plot(induction_levels,mean_active_expression,'-'); hold on;
plot(0:0.1:72,model_levels,'r-');
xlabel('Time (hours)');  ylabel('OFP MEFL');
xlim([0 75]); ylim([1e5 2e7]);
title('Expression Model');
outputfig(h,'rtTA-population-mean-model');
set(gca,'YScale','log'); ylim([1e5 1e8]);
outputfig(h,'rtTA-population-mean0log-consensus');

h = figure('PaperPosition',[1 1 5 3.66]);
plot(sample_inductions,sample_activity,'*'); hold on;
plot(induction_levels,fraction_active,'-'); hold on;
plot(0:0.1:72,model_acts,'r-');
xlabel('Time (hours)');  ylabel('OFP MEFL');
xlim([0 75]);
title('Activation Model');
outputfig(h,'rtTA-fraction-active-model');


%%%%%
% Test a timing hypothesis:
% OFP levels should rise quickly for all subpopulations, but then stop as the IFP rises to levels of significant repression.
% It does appear to go down some, but the amounts are equivocal.

n_bins = get_n_bins(getBins(AP));
IFPs = zeros(n_bins,n_levels);
OFPs = zeros(n_bins,n_levels);
for i=1:numel(induction_levels)
    IFPs(:,i) = sampleresults{i}{1}.Means(:,1);
    OFPs(:,i) = sampleresults{i}{1}.Means(:,3);
end

load('../Constitutive/ControlSeries.mat');

bin_levels = get_bin_centers(getBins(AP));

h = figure('PaperPosition',[1 1 5 3.66]);
for i=1:n_bins
    semilogy(induction_levels(2:end),IFPs(i,2:end)./mean_activities(1,:)./bin_levels(i),'b*-'); hold on;
    semilogy(induction_levels(2:end),OFPs(i,2:end)./mean_activities(1,:)./bin_levels(i),'g*-');
end

h = figure('PaperPosition',[1 1 5 3.66]);
for i=1:4:n_bins
    semilogy(induction_levels(2:end),OFPs(i,2:end)./mean_activities(1,:),'g*'); hold on;
end

h = figure('PaperPosition',[1 1 5 3.66]);
for i=1:n_bins
    semilogy(induction_levels(2:end),IFPs(i,2:end),'b*-'); hold on;
    semilogy(induction_levels(2:end),OFPs(i,2:end),'g*-');
end



%%%%%%%%% Secondary report:
% expression = get_channel_results(results,'input');
% o_index = find(CM,input); % Determine data column from ColorModel
% 
% fraction_active = zeros(n_levels,1);
% mean_active_expression = zeros(n_levels,1);
% n_samples = 0;
% sample_inductions = []; sample_activity = []; sample_expression = [];
% for i=1:n_levels,
%     which = counts(:,i)>0;
%     fraction_active(i) = sum(counts(which,i) .* active(which,i)) / sum(counts(which,i));
%     which = active(:,i) > 0.9 & counts(:,i)>getMinValidCount(AP)*numel(sampleresults{i});
%     mean_active_expression(i) = 10.^wmean(log10(expression(which,i)),counts(which,i));
%     for j=1:numel(sampleresults{i}),
%         n_samples = n_samples+1;
%         sample_inductions(n_samples) = level_file_pairs{i,1};
%         sample = sampleresults{i}{j};
% 
%         which = sample.BinCounts>getMinValidCount(AP);
%         sample_activity(n_samples) = sum(sample.BinCounts(which) .* sample.FractionActive(which)) / sum(sample.BinCounts(which));
%         which = sample.FractionActive>0.9;
%         sample_expression(n_samples) = 10.^wmean(log10(sample.Means(which,o_index)),sample.BinCounts(which));
%     end
% end
% 
% h = figure('PaperPosition',[1 1 5 3.66]);
% plot(induction_levels,fraction_active,'-'); hold on;
% plot(sample_inductions,sample_activity,'*');
% xlabel('Time (hours)');  ylabel('Fraction Active');
% xlim([0 75]); ylim([0 1]);
% title('TAL21 fraction active vs time');
% outputfig(h,'TAL21-fraction-active');
% 
% h = figure('PaperPosition',[1 1 5 3.66]);
% plot([level_file_pairs{:,1}],mean_active_expression,'-'); hold on;
% plot(sample_inductions,sample_expression,'*');
% xlabel('Time (hours)');  ylabel('OFP MEFL');
% xlim([0 75]);
% title('TAL21 active population mean MEFL vs time');
% outputfig(h,'TAL21-population-mean');
% set(gca,'YScale','log');
% outputfig(h,'TAL21-population-mean-log');
 